01_2024_Quantamental/quantamental/quantamental/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path(route="", view=include("scores.urls")),
    path(route="admin/", view=admin.site.urls),
    path(route="accounts/", view=include("django.contrib.auth.urls")),
]

01_2024_Quantamental/quantamental/scores/urls.py
from django.urls import path

from . import views

app_name = "scores"

urlpatterns = [
    path(route="signup/", view=views.SignUpView.as_view(), name="signup_view"),
    path(route="scores/", view=views.scores_view, name="scores_view"),
    path(route="stock/", view=views.single_stock_view, name="single_stock_view"),
    path(
        route="stockdata1/",
        view=views.single_stock_view_data_1,
        name="single_stock_view_data_1",
    ),
    path(
        route="stockdata2/",
        view=views.single_stock_view_data_2,
        name="single_stock_view_data_2",
    ),
    path(route="table/", view=views.table_view, name="table_view"),
    path(route="data/", view=views.table_view_data, name="table_data"),
    path(route="data2/", view=views.table_view_data_2, name="table_data2"),
    path(route="pf/", view=views.pf_view, name="pf_view"),
]

01_2024_Quantamental/quantamental/scores/models.py
# Create your models here.
import csv

from django.contrib.auth.models import User
from django.db import models


class Identification(models.Model):
    code = models.CharField(max_length=200, null=True)
    name = models.CharField(max_length=200, null=True)
    isin = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.code


class Sector(models.Model):
    code = models.ForeignKey(Identification, null=True, on_delete=models.CASCADE)
    sector = models.CharField(max_length=200, null=True)
    industry = models.CharField(max_length=200, null=True)
    gicSector = models.CharField(max_length=200, null=True)
    gicGroup = models.CharField(max_length=200, null=True)
    gicIndustry = models.CharField(max_length=200, null=True)
    gicSubIndustry = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.code.code


class Qualdata(models.Model):
    ticker = models.CharField(max_length=200, null=True)
    name = models.CharField(max_length=200, null=True)
    description = models.CharField(max_length=500, null=True)
    exchange = models.CharField(max_length=200, null=True)
    sector = models.CharField(max_length=200, null=True)
    beta = models.FloatField(null=True)
    mcap = models.FloatField(null=True)
    dividendYield = models.FloatField(null=True)

    def __str__(self):
        return self.ticker


class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    profile_pic = models.ImageField(default="default.jpg")
    name = models.CharField(
        max_length=200, null=True
    )  # null=True means that the field can be empty
    phone = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    date_created = models.DateTimeField(
        auto_now_add=True, null=True
    )  # auto_now_add=True means that the date will be added automatically when the object is created

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    CATEGORY = (("Indoor", "Indoor"), ("Outdoor", "Outdoor"))
    category = models.CharField(max_length=200, null=True, choices=CATEGORY)
    name = models.CharField(max_length=200, null=True)
    price = models.FloatField(null=True)
    description = models.CharField(max_length=200, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.name


class Order(models.Model):
    STATUS = (
        ("Pending", "Pending"),
        ("Out for delivery", "Out for delivery"),
        ("Delivered", "Delivered"),
    )
    status = models.CharField(max_length=200, null=True, choices=STATUS)
    customer = models.ForeignKey(Customer, null=True, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, null=True, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    note = models.CharField(max_length=100, null=True)

    def __str__(self):
        return f"From: [{self.customer.name}] Product: [{self.product.name}]"

01_2024_Quantamental/quantamental/scores/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from . import models


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)

        self.fields["username"].widget.attrs["class"] = "form-control"
        self.fields["password1"].widget.attrs["class"] = "form-control"
        self.fields["password2"].widget.attrs["class"] = "form-control"
        self.fields["email"].widget.attrs["class"] = "form-control"

01_2024_Quantamental/quantamental/scores/views.py
import json

from django import forms
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from . import models
from .forms import UserRegisterForm


@login_required
def table_view(request):
    context = {"view_name": "table"}
    return render(
        request=request,
        template_name="scores/table_view.html",
        context=context,
    )


@login_required
def table_view_data(request):
    default_columns = [
        "code__code",
        "code__isin",
        "code__name",
        "sector",
        "industry",
        "gicSector",
        "gicGroup",
        "gicIndustry",
        "gicSubIndustry",
    ]
    data = list(models.Sector.objects.values(*default_columns))
    return JsonResponse(data, safe=False)


@login_required
def table_view_data_2(request):
    default_columns = ["code", "isin", "name"]
    data = list(models.Identification.objects.values(*default_columns))
    return JsonResponse(data, safe=False)


@login_required
def pf_view(request):
    return render(request=request, template_name="scores/pf_view.html")


@login_required
def scores_view(request):
    context = {"user": request.user}
    print(context)
    return render(
        request=request, template_name="scores/scores_view.html", context=context
    )


@login_required
def single_stock_view(request):
    context = {"view_name": "single_stock"}
    return render(
        request=request,
        template_name="scores/single_stock_view.html",
        context=context,
    )


@login_required
def single_stock_view_data_1(request):
    default_columns = [
        "description",
    ]
    ticker = request.GET.get("ticker")
    print(ticker)
    data = list(models.Qualdata.objects.filter(ticker=ticker).values(*default_columns))
    return JsonResponse(data, safe=False)


@login_required
def single_stock_view_data_2(request):
    default_columns = [
        "name",
        "ticker",
        "exchange",
        "sector",
        "beta",
        "mcap",
        "dividendYield"
    ]
    ticker = request.GET.get("ticker")
    data = list(models.Qualdata.objects.filter(ticker=ticker).values(*default_columns))
    return JsonResponse(data, safe=False)


@login_required
def vis_view(request):
    context = {
        "products": models.Product.objects.all(),
        "headers": ["Product", "Category", "Price"],
        "headersl": ["product", "category", "price"],
    }
    return render(
        request=request,
        template_name="scores/vis_view.html",
        context=context,
    )


# FORMS:
class SignUpView(CreateView):
    form_class = UserRegisterForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

01_2024_Quantamental/quantamental/scores/templates/scores/pf_view.html
{% extends "base.html" %}

{% block content%}
<div class="container-fluid">
    <h1>PF_VIEW.HTML</h1>
</div>

{% endblock content %}

01_2024_Quantamental/quantamental/scores/templates/scores/scores_view.html
{% extends "base.html" %}

{% block content%}
<div class="container-fluid">
    <h1>INDIVIDUAL_VIEW.HTML</h1>
</div>

<script>
    alert("Logged in as: {{ request.user.username }}");  // Alert with the logged-in user's username
</script>

{% endblock content %}

01_2024_Quantamental/quantamental/scores/templates/scores/single_stock_view.html
{% extends "base.html" %}
{% load static %}
{% block head %}
<!-- CSS Files -->
<link rel="stylesheet" href="{% static 'scores/css/singleStock.css' %}">


{% endblock head %}


{% block content %}

<div class="container-fluid">
    <!-- Control panel for content -->

    <div class="row justify-content-center">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col">
                        <h6>Stock:</h6>
                        <select class="form-select" aria-label="Default select example">
                            <option value="AMD">AMD</option>
                            <option value="AAPL">Apple</option>
                            <option value="AVGO">Broadcomm</option>
                            <option value="IBM">IBM</option>
                            <option value="INTC">Intel</option>
                            <option value="NVDA">NVIDIA</option>
                            <option value="QCOM">Qualcomm</option>
                            <option value="TXN">Texas Instruments</option>
                        </select>
                    </div>

                    <div class="col">
                        <h6>Reference:</h6>
                        <select class="form-select" aria-label="Default select example">
                            <option value="1">MSCI World</option>
                            <option value="2">NASDAQ 100</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>



    <!-- <div class="row pb-5">
        <div class="col">
            <h2>Control Panel</h2>
            <h3>Stock</h3>

            <select class="form-select" aria-label="Default select example">
                <option value="AMD">AMD</option>
                <option value="AAPL">Apple</option>
                <option value="AVGO">Broadcomm</option>
                <option value="IBM">IBM</option>
                <option value="INTC">Intel</option>
                <option value="NVDA">NVIDIA</option>
                <option value="QCOM">Qualcomm</option>
                <option value="TXN">Texas Instruments</option>
            </select>
            <h3>Client Portfolio</h3>
            <select class="form-select" aria-label="Default select example">
                <option value="1">MSCI World</option>
                <option value="2">NASDAQ 100</option>
            </select>

        </div>
    </div> -->

    <div class="h-divider">
        <h3>Overview</h3>
        <div class="divider-shadow"></div>
    </div>

    <div class="row">
        <div class="col-1"></div>
        <div class="col-4">
            <table class="table" style="width:100%" data-url="{% url 'scores:single_stock_view_data_2' %}" id="miau2">
                <thead>
                    <tr class="table-headers"></tr>
                </thead>
                <tbody class="table-body"></tbody>
            </table>

            <table class="table" style="width:100%" data-url="{% url 'scores:single_stock_view_data_1' %}" id="miau1">
                <thead>
                    <tr class="table-headers"></tr>
                </thead>
                <tbody class="table-body"></tbody>
            </table>
        </div>

        <div class="col-7">
            <div id="sankey-chart-area" class="col text-center"></div>
        </div>
    </div>


    <div class="h-divider">
        <h3>Performance</h3>
        <div class="divider-shadow"></div>
    </div>

    <!-- Performance -->
    <div class="row">
        <div class="col">
            <div id="performance-line-area"></div>

            <div class="pb-1" id="slider-div">
                <div class="slider-container">
                    <label>Date: <span id="dateLabel1">31/12/2009</span> - <span
                            id="dateLabel2">07/03/2024</span></label>

                </div>
                <div class="slider-container">
                    <div id="date-slider1"></div>
                </div>
            </div>
        </div>
        <div class="col">
            <div id="performance-bar-area"></div>
        </div>
    </div>

    <div class="h-divider">
        <h3>Fundamentals</h3>
        <div class="divider-shadow"></div>
    </div>

    <!-- Multiples -->
    <div class="row">
        <div class="col">
            <div id="multiple-bar-area"></div>
        </div>
        <div class="col">
            <div id="spider-area"></div>
        </div>
    </div>

</div>

{% endblock content %}





{% block jsextra %}

<script>
    const output1 = "{% url 'scores:single_stock_view_data_1' %}";
    const output2 = "{% url 'scores:single_stock_view_data_2' %}";
    const sankeyData = "{% static 'data/sankeyApple.json' %}";
    const sankeyTest = "{% static 'data/sankey.json' %}";
    const sankeyStocks = "{% static 'data/sankeyStocks.json' %}";
    const techstockTS = "{% static 'data/techstockTS2.csv' %}";
    const groupedbar = "{% static 'data/groupedbarstock.json' %}";
    const groupedbar2 = "{% static 'data/multiples.json' %}";
</script>

<!-- <script>
    var csvUrl = "{% static 'data/revenues.csv' %}";
    var jsonUrl2 = "{% static 'data/coins.json' %}";
    var indices = "{% static 'data/indices.csv' %}";
</script> -->
<!-- <script type="text/javascript" src="{% static 'js/line_brushed.js' %}"></script> -->
<script type="text/javascript" src="{% static 'js/BarChart.js' %}"></script>
<script type="text/javascript" src="{% static 'js/LineChart.js' %}"></script>
<script type="text/javascript" src="{% static 'js/HorizontalTable.js' %}"></script>
<!-- <script type="text/javascript" src="{% static 'js/Sankey.js' %}"></script> -->
<script type="text/javascript" src="{% static 'js/SankeyChart.js' %}"></script>
<script type="text/javascript" src="{% static 'js/GroupedBarChart.js' %}"></script>
<script type="text/javascript" src="{% static 'js/SpiderChart.js' %}"></script>

<!-- <script type="text/javascript" src="{% static 'scores/js/main_vis.js' %}"></script> -->
<script type="text/javascript" src="{% static 'scores/js/main_single_stock.js' %}"></script>
{% endblock jsextra %}

01_2024_Quantamental/quantamental/scores/templates/scores/table_view.html
{% extends "base.html" %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'scores/css/test.css' %}">

{% endblock head %}


{% block content %}
<div class="container-fluid">


    <div class="row scores justify-content-center">
        <div class="col">
            <!-- Data -->
            {% url 'scores:table_data' as data_url %}
            <!-- Table -->
            {% include 'table.html' with data_url=data_url view_name=view_name %}
        </div>
    </div>


    <div class="row scores justify-content-center">
        <div class="col">
            <!-- Data -->
            {% url 'scores:table_data2' as data_url %}
            <!-- Table -->
            {% include 'table.html' with data_url=data_url view_name=view_name %}
        </div>
    </div>



</div>
{% endblock content %}



{% block jsextra %}
{% endblock jsextra %}

01_2024_Quantamental/quantamental/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">




<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <!-------- Lineicons CSS -------->
    <link rel="stylesheet" href="https://cdn.lineicons.com/4.0/lineicons.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

    <!-------- DataTables CSS -------->
    <!-- DataTables -->
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css">
    <!-- Bootstrap 5 -->
    <!-- <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/dataTables.bootstrap5.min.css"> -->
    <!-- Searchpanes -->
    <link rel="stylesheet" href="https://cdn.datatables.net/searchpanes/2.2.0/css/searchPanes.dataTables.min.css">
    <!-- Select -->
    <link rel="stylesheet" href=" https://cdn.datatables.net/select/1.7.0/css/select.dataTables.min.css">
    <!-- Buttons -->
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css">
    <!-- Responsive -->
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.5.0/css/responsive.dataTables.min.css">
    <!-- ColReorder -->
    <link rel="stylesheet" href="https://cdn.datatables.net/colreorder/1.7.0/css/colReorder.dataTables.min.css">
    <!-- KeyTable -->
    <link rel="stylesheet" href="https://cdn.datatables.net/keytable/2.11.0/css/keyTable.dataTables.min.css">
    <!-- StateRestore -->
    <link rel="stylesheet" href="https://cdn.datatables.net/staterestore/1.3.0/css/stateRestore.dataTables.min.css">






    <!-------- jQuery UI CSS -------->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">


    <!-------- Bootstrap CSS -------->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">


    <!-------- Custom CSS -------->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    {% block head %}
    {% endblock head %}
</head>

<body>
    <div class="wrapper">
        <aside id="sidebar">
            <div class="d-flex">
                <button class="toggle-btn" type="button">
                    <i class="lni lni-grid-alt"></i>
                </button>
                <div class="sidebar-logo">
                    <a href="#">CROSSINVEST</a>
                </div>
            </div>
            <ul class="sidebar-nav">
                <!-- Simple Link -->
                <li class="sidebar-item">
                    <a href="{% url 'scores:scores_view' %}" class="sidebar-link">
                        <i class="bi bi-person"></i>
                        <span>Individual</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a href="{% url 'scores:table_view' %}" class="sidebar-link">
                        <!-- <i class="bi bi-filter-square"></i> -->
                        <i class="bi bi-sliders"></i>
                        <span>Universe</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a href="{% url 'scores:single_stock_view' %}" class="sidebar-link">
                        <i class="bi bi-bar-chart-line"></i>
                        <span>Single Stock</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a href="{% url 'scores:pf_view' %}" class="sidebar-link">
                        <i class="bi bi-pie-chart"></i>
                        <span>Portfolio</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a href="#" class="sidebar-link">
                        <i class="bi bi-list-check"></i>
                        <span>Task</span>
                    </a>
                </li>
                <!-- <li class="sidebar-item">
                    <a href="#" class="sidebar-link collapsed has-dropdown" data-bs-toggle="collapse"
                        data-bs-target="#auth" aria-expanded="false" aria-controls="auth">
                        <i class="lni lni-protection"></i>
                        <span>Auth</span>
                    </a>
                    <ul id="auth" class="sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">
                        <li class="sidebar-item">
                            <a href="#" class="sidebar-link">Login</a>
                        </li>
                        <li class="sidebar-item">
                            <a href="#" class="sidebar-link">Register</a>
                        </li>
                    </ul>
                </li> -->
                <!-- <li class="sidebar-item">
                    <a href="#" class="sidebar-link collapsed has-dropdown" data-bs-toggle="collapse"
                        data-bs-target="#multi" aria-expanded="false" aria-controls="multi">
                        <i class="lni lni-layout"></i>
                        <span>Multi Level</span>
                    </a>
                    <ul id="multi" class="sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">
                        <li class="sidebar-item">
                            <a href="#" class="sidebar-link collapsed" data-bs-toggle="collapse"
                                data-bs-target="#multi-two" aria-expanded="false" aria-controls="multi-two">
                                Two Links
                            </a>
                            <ul id="multi-two" class="sidebar-dropdown list-unstyled collapse">
                                <li class="sidebar-item">
                                    <a href="#" class="sidebar-link">Link 1</a>
                                </li>
                                <li class="sidebar-item">
                                    <a href="#" class="sidebar-link">Link 2</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li> -->
                <li class="sidebar-item">
                    <a href="#" class="sidebar-link">
                        <i class="bi bi-bell"></i>
                        <span>Notification</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a href="#" class="sidebar-link">
                        <i class="bi bi-gear"></i>
                        <span>Setting</span>
                    </a>
                </li>
            </ul>
            <div class="sidebar-footer">
                <form action="{% url 'logout' %}" method="POST">
                    {% csrf_token %}
                    <a id="logout-link" class="sidebar-link" href="#">
                        <button class="btn-logout" type="submit"><i class="bi bi-box-arrow-left"></i>
                            <span>Logout</span>
                        </button>
                    </a>
                </form>
            </div>
        </aside>
        <div class="main p-3">

            {% block content %}

            {% endblock content %}

        </div>

        <!-------- jQuery JS -------->
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

        <!-- jQuery UI -->
        <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>


        <!-------- DataTables JS -------->
        <script type="text/javascript" src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
        <!-- Bootstrap -->
        <!-- <script type="text/javascript" src="https://cdn.datatables.net/1.13.7/js/dataTables.bootstrap5.min.js"></script> -->
        <!-- Searchpanes -->
        <script type="text/javascript"
            src="https://cdn.datatables.net/searchpanes/2.2.0/js/dataTables.searchPanes.min.js"></script>
        <!-- Select -->
        <script type="text/javascript" src="//cdn.datatables.net/select/1.7.0/js/dataTables.select.js"></script>
        <!-- Buttons -->
        <script type="text/javascript"
            src="https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
        <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
        <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.print.min.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.colVis.min.js"></script>
        <!-- Responsive -->
        <script type="text/javascript"
            src="https://cdn.datatables.net/responsive/2.5.0/js/dataTables.responsive.min.js"></script>
        <!-- ColReorder -->
        <script type="text/javascript"
            src="https://cdn.datatables.net/colreorder/1.7.0/js/dataTables.colReorder.min.js"></script>
        <!-- KeyTable -->
        <script type="text/javascript"
            src="https://cdn.datatables.net/keytable/2.11.0/js/dataTables.keyTable.min.js"></script>
        <!-- StateRestore -->
        <script type="text/javascript"
            src="https://cdn.datatables.net/staterestore/1.3.0/js/dataTables.stateRestore.min.js"></script>




        <!-------- Bootstrap JS -------->
        <script type="text/javascript"
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
            crossorigin="anonymous"></script>

        <!-------- AXIOS JS -------->
        <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>


        <!-------- Custom JS -------->
        <script type="text/javascript" src="{% static 'js/base.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/test2.js' %}"></script>

        <!-------- D3 -------->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/7.8.5/d3.min.js"></script>
        <script src=" https://cdnjs.cloudflare.com/ajax/libs/d3-sankey/0.12.3/d3-sankey.min.js"></script>







        <!-- <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script> -->





        {% block jsextra %}
        {% endblock jsextra %}


</body>

</html>

01_2024_Quantamental/quantamental/templates/base_auth.html
{% load static %}
<!DOCTYPE html>
<html lang="en">




<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.lineicons.com/4.0/lineicons.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base_auth.css' %}">
    {% block head %}
    {% endblock head %}
</head>

<body>
    <section class="container-fluid px-0">
        <div class="row align-items-center">
            <div class="col-6 d-flex justify-content-center">

                {% block first-col %}
                <div id="form-div">
                    {% block form-div-content %}

                    {% endblock form-div-content %}
                </div>
                {% endblock first-col %}
            </div>
            <div class="col-6">
                {% if request.resolver_match.url_name == 'login' %}
                <a class="sign" href="{% url 'scores:signup_view' %}">Sign up</a>
                {% else %}
                <a class="sign" href="{% url 'login' %}">Login</a>
                {% endif %}
                <img class="img-fluid" src="{% static 'img/crossinvest_stemma_nuovo-1.jpg' %}" alt="Image not found">
            </div>
        </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/base_auth.js' %}"></script>
</body>



</html>

01_2024_Quantamental/quantamental/templates/table.html
<table class="table-general" style="width:100%" data-url="{{ data_url }}" id="table-{{ view_name }}-">
    <thead>
        <tr class="table-headers"></tr>
    </thead>
    <tbody class="table-body"></tbody>
    <tfoot>
        <tr class="table-footer"></tr>
    </tfoot>
</table>